---
# tasks file for tripleo-upgrade
- name: launch pre upgrade workload
  command: "{{ workload_launch_script }}"
  when: workload_launch

- include: upgrade/main.yml
  when: upgrade_noop|bool or undercloud_upgrade|bool or overcloud_upgrade|bool

- include: update/main.yml
  when: update_noop|bool or undercloud_update|bool or overcloud_update|bool

- include: fast-forward-upgrade/main.yml
  when: ffu_undercloud_upgrade|bool or ffu_overcloud_upgrade|bool
